name: Laravel

on: ['push', 'pull_request']

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2 
    - uses: php-actions/composer@v6
    - name: Execute tests (Unit and Feature tests) via PHPUnit 
      run: composer u
      run: ./vendor/bin/pest
